require 'nokogiri'
require 'word_wrap'
require 'word_wrap/core_ext'
require 'watir'
require 'phantomjs'

require_relative '../lib/cli.rb'
require_relative '../lib/table.rb'
require_relative '../lib/stock_attribute.rb'
require_relative '../lib/stock_description.rb'
require_relative '../lib/dev_cli.rb'
require_relative '../lib/main_cli.rb'
require_relative '../lib/stock_quote.rb'
require_relative '../lib/stock_related_company.rb'
require_relative '../lib/scraper.rb'
require_relative '../lib/stock.rb'
